data_dir: data/cifar10
dataset: CIFAR10
model: DctResnet20
num_classes: 10
img_size: 32
T: 2

seed: 3407
channels_last: False
batch_size: 128
opt: sgd #adam
opt_eps: 1e-8
weight_decay: 0
lr: 0.1 # 3e-4
min_lr: 1e-5
sched: cosine
epochs: 600
cooldown_epochs: 10
warmup_lr: 1e-5
warmup_epochs: 10
workers: 8

